//! The IFC2X3 occurrence/type mapping of the IDS implementers' documentation.
//!
//! Source: buildingSMART IDS, `Documentation/ImplementersDocumentation/
//! ifc2x3-occurrence-type-mapping-table.md` (commit 870f9c4e). Only the entity
//! names are recorded here, upper-cased: facts about the schemas, not the text
//! of the document.

/// IFC4 occurrence names that an IDS may use for IFC2X3, with the IFC2X3
/// occurrence and type entities they stand for: `(name, occurrence, type)`.
pub(super) const IFC2X3_OCCURRENCE_TYPES: [(&str, &str, &str); 57] = [
    ("IFCFURNITURE", "IFCFURNISHINGELEMENT", "IFCFURNITURETYPE"),
    (
        "IFCSYSTEMFURNITUREELEMENT",
        "IFCFURNISHINGELEMENT",
        "IFCSYSTEMFURNITUREELEMENTTYPE",
    ),
    (
        "IFCACTUATOR",
        "IFCDISTRIBUTIONCONTROLELEMENT",
        "IFCACTUATORTYPE",
    ),
    ("IFCALARM", "IFCDISTRIBUTIONCONTROLELEMENT", "IFCALARMTYPE"),
    (
        "IFCCONTROLLER",
        "IFCDISTRIBUTIONCONTROLELEMENT",
        "IFCCONTROLLERTYPE",
    ),
    (
        "IFCFLOWINSTRUMENT",
        "IFCDISTRIBUTIONCONTROLELEMENT",
        "IFCFLOWINSTRUMENTTYPE",
    ),
    (
        "IFCSENSOR",
        "IFCDISTRIBUTIONCONTROLELEMENT",
        "IFCSENSORTYPE",
    ),
    (
        "IFCAIRTOAIRHEATRECOVERY",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCAIRTOAIRHEATRECOVERYTYPE",
    ),
    ("IFCBOILER", "IFCENERGYCONVERSIONDEVICE", "IFCBOILERTYPE"),
    ("IFCCHILLER", "IFCENERGYCONVERSIONDEVICE", "IFCCHILLERTYPE"),
    ("IFCCOIL", "IFCENERGYCONVERSIONDEVICE", "IFCCOILTYPE"),
    (
        "IFCCONDENSER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCCONDENSERTYPE",
    ),
    (
        "IFCCOOLEDBEAM",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCCOOLEDBEAMTYPE",
    ),
    (
        "IFCCOOLINGTOWER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCCOOLINGTOWERTYPE",
    ),
    (
        "IFCELECTRICGENERATOR",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCELECTRICGENERATORTYPE",
    ),
    (
        "IFCELECTRICMOTOR",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCELECTRICMOTORTYPE",
    ),
    (
        "IFCEVAPORATIVECOOLER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCEVAPORATIVECOOLERTYPE",
    ),
    (
        "IFCEVAPORATOR",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCEVAPORATORTYPE",
    ),
    (
        "IFCHEATEXCHANGER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCHEATEXCHANGERTYPE",
    ),
    (
        "IFCHUMIDIFIER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCHUMIDIFIERTYPE",
    ),
    (
        "IFCMOTORCONNECTION",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCMOTORCONNECTIONTYPE",
    ),
    (
        "IFCSPACEHEATER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCSPACEHEATERTYPE",
    ),
    (
        "IFCTRANSFORMER",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCTRANSFORMERTYPE",
    ),
    (
        "IFCTUBEBUNDLE",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCTUBEBUNDLETYPE",
    ),
    (
        "IFCUNITARYEQUIPMENT",
        "IFCENERGYCONVERSIONDEVICE",
        "IFCUNITARYEQUIPMENTTYPE",
    ),
    (
        "IFCAIRTERMINALBOX",
        "IFCFLOWCONTROLLER",
        "IFCAIRTERMINALBOXTYPE",
    ),
    ("IFCDAMPER", "IFCFLOWCONTROLLER", "IFCDAMPERTYPE"),
    (
        "IFCELECTRICTIMECONTROL",
        "IFCFLOWCONTROLLER",
        "IFCELECTRICTIMECONTROLTYPE",
    ),
    ("IFCFLOWMETER", "IFCFLOWCONTROLLER", "IFCFLOWMETERTYPE"),
    (
        "IFCPROTECTIVEDEVICE",
        "IFCFLOWCONTROLLER",
        "IFCPROTECTIVEDEVICETYPE",
    ),
    (
        "IFCSWITCHINGDEVICE",
        "IFCFLOWCONTROLLER",
        "IFCSWITCHINGDEVICETYPE",
    ),
    ("IFCVALVE", "IFCFLOWCONTROLLER", "IFCVALVETYPE"),
    (
        "IFCCABLECARRIERFITTING",
        "IFCFLOWFITTING",
        "IFCCABLECARRIERFITTINGTYPE",
    ),
    ("IFCDUCTFITTING", "IFCFLOWFITTING", "IFCDUCTFITTINGTYPE"),
    ("IFCJUNCTIONBOX", "IFCFLOWFITTING", "IFCJUNCTIONBOXTYPE"),
    ("IFCPIPEFITTING", "IFCFLOWFITTING", "IFCPIPEFITTINGTYPE"),
    ("IFCCOMPRESSOR", "IFCFLOWMOVINGDEVICE", "IFCCOMPRESSORTYPE"),
    ("IFCFAN", "IFCFLOWMOVINGDEVICE", "IFCFANTYPE"),
    ("IFCPUMP", "IFCFLOWMOVINGDEVICE", "IFCPUMPTYPE"),
    (
        "IFCCABLECARRIERSEGMENT",
        "IFCFLOWSEGMENT",
        "IFCCABLECARRIERSEGMENTTYPE",
    ),
    ("IFCCABLESEGMENT", "IFCFLOWSEGMENT", "IFCCABLESEGMENTTYPE"),
    ("IFCDUCTSEGMENT", "IFCFLOWSEGMENT", "IFCDUCTSEGMENTTYPE"),
    ("IFCPIPESEGMENT", "IFCFLOWSEGMENT", "IFCPIPESEGMENTTYPE"),
    (
        "IFCELECTRICFLOWSTORAGEDEVICE",
        "IFCFLOWSTORAGEDEVICE",
        "IFCELECTRICFLOWSTORAGEDEVICETYPE",
    ),
    ("IFCTANK", "IFCFLOWSTORAGEDEVICE", "IFCTANKTYPE"),
    ("IFCAIRTERMINAL", "IFCFLOWTERMINAL", "IFCAIRTERMINALTYPE"),
    (
        "IFCELECTRICAPPLIANCE",
        "IFCFLOWTERMINAL",
        "IFCELECTRICAPPLIANCETYPE",
    ),
    (
        "IFCFIRESUPPRESSIONTERMINAL",
        "IFCFLOWTERMINAL",
        "IFCFIRESUPPRESSIONTERMINALTYPE",
    ),
    ("IFCLAMP", "IFCFLOWTERMINAL", "IFCLAMPTYPE"),
    ("IFCLIGHTFIXTURE", "IFCFLOWTERMINAL", "IFCLIGHTFIXTURETYPE"),
    ("IFCOUTLET", "IFCFLOWTERMINAL", "IFCOUTLETTYPE"),
    (
        "IFCSANITARYTERMINAL",
        "IFCFLOWTERMINAL",
        "IFCSANITARYTERMINALTYPE",
    ),
    (
        "IFCSTACKTERMINAL",
        "IFCFLOWTERMINAL",
        "IFCSTACKTERMINALTYPE",
    ),
    (
        "IFCWASTETERMINAL",
        "IFCFLOWTERMINAL",
        "IFCWASTETERMINALTYPE",
    ),
    (
        "IFCDUCTSILENCER",
        "IFCFLOWTREATMENTDEVICE",
        "IFCDUCTSILENCERTYPE",
    ),
    ("IFCFILTER", "IFCFLOWTREATMENTDEVICE", "IFCFILTERTYPE"),
    (
        "IFCVIBRATIONISOLATOR",
        "IFCEQUIPMENTELEMENT",
        "IFCVIBRATIONISOLATORTYPE",
    ),
];
